source 'https://rubygems.org'

gem 'activesupport'
gem 'builder'
gem 'json'
gem 'multi_json'
gem 'mysql'
gem 'php-serialize'
gem 'rack'
gem 'rack-throttle'
gem 'simple_oauth'
gem 'sinatra'
gem 'twitter'
gem 'koala'
gem 'xml-simple'