source 'https://rubygems.org'

gem 'unicorn'
gem 'activesupport'
gem 'builder'
gem 'json'
gem 'multi_json'
gem 'mysql2'
gem 'oauth'
gem 'php-serialize'
gem 'rack'
gem 'rack-throttle'
gem 'simple_oauth'
gem 'sinatra', git: 'git://github.com/sinatra/sinatra.git'
gem 'sinatra-cross_origin'
gem 'twitter'
gem 'koala'
gem 'xml-simple'
gem 'nokogiri'
gem 'facets'
gem 'htmlentities'
gem 'bcrypt'
